plugins {
    id 'com.android.application'
}

android {
    namespace 'es.iesvirgendelacaridad.corrector'
    compileSdk 35

    defaultConfig {
        applicationId 'es.iesvirgendelacaridad.corrector'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
