package es.iesvirgendelacaridad.corrector;

import org.json.JSONObject;
import java.util.Locale;

public final class PlusPrompts {
    private PlusPrompts() {}

    private static final String CORE = "Marco: Química 2.º Bachillerato, LOMLOE-Andalucía. Toda puntuación exige evidencia observable. Corrige cada cuestión independientemente, sin efecto halo. No otorgues puntos por conocimientos no expresados. Clasifica errores conceptuales, químicos, matemáticos/algebraicos, unidades, signo, formulación, nomenclatura, cálculo, redondeo y error arrastrado. Un error inicial no se penaliza repetidamente si el procedimiento posterior es correcto y coherente; sí puede penalizarse de nuevo si introduce una nueva decisión científicamente errónea, contradicción no detectada o resultado imposible no cuestionado. Audita siempre la solución modelo de forma independiente. Mantén rigor en ecuaciones, ajuste, unidades, constantes, aproximaciones, cifras significativas, IUPAC, equilibrio, ácido-base, redox, electroquímica y orgánica. ";

    private static final String CRITERIA = "Criterios disponibles: 1.1 importancia/conexiones de la Química; 1.2 procesos y propiedades desde conocimientos químicos; 1.3 naturaleza experimental/interdisciplinar; 2.1 problemas actuales ciencia-tecnología; 2.2 comunicación/contexto social-económico-ético; 2.3 aplicación razonada de modelos y leyes; 3.1 nomenclatura IUPAC; 3.2 herramientas matemáticas, ecuaciones y unidades; 3.3 seguridad y gestión de residuos; 4.1 composición, propiedades y aplicaciones; 4.2 argumentación sobre efectos ambientales/salud; 4.3 beneficios de tecnología química; 5.1 trabajo interdisciplinar; 5.2 pensamiento científico y crítico; 5.3 resolución colaborativa; 5.4 representación/visualización con recursos; 6.1 razonamiento de conceptos fundamentales con leyes de otras ciencias; 6.2 relaciones con otras disciplinas; 6.3 resolución de problemas y cuestiones con matemáticas y tecnología. Usa como máximo dos criterios principales por cuestión y no inventes códigos. Mapeos relevantes: nomenclatura→3.1; herramientas matemáticas→3.2; ácido-base B.4.1/B.4.2→4.1, B.4.3→6.2, B.4.4→1.2, B.4.5→1.1/3.3, B.4.6→1.1; redox B.5.1→1.2, B.5.2→3.2, B.5.3→2.3/3.1, B.5.4→2.3, B.5.5→2.2. ";

    public static String fmc(String title, String unit, String type, String duration, double total, String level, String presentation, String sha, boolean autoAllocate) {
        return String.format(Locale.ROOT,
            "ACTÚA COMO CORRECTOR CRITERIAL DE QUÍMICA DE 2.º DE BACHILLERATO. Usa el archivo maestro adjunto como fuente de verdad.\n\nOBJETIVO: construir y auditar una FICHA MAESTRA DE CORRECCIÓN (FMC). No corrijas todavía alumnado.\n\nCONFIGURACIÓN: título=%s; unidad=%s; tipo=%s; duración=%s min; total=%.4f puntos; exigencia=%s; presentación=%s; SHA-256=%s; ponderaciones ausentes=%s.\n\nREGLAS: lee íntegramente el examen; extrae todas las cuestiones/subapartados; resuelve de forma independiente; audita soluciones y datos; para cada cuestión crea evidencias con valor fijo cuya suma coincida con max_points; la nota será suma de evidencias, no descuentos subjetivos; PARCIALMENTE_ACREDITADA solo si defines partial_allowed=true y partial_points fijo; fija cap_if_missing para evidencias esenciales cuando proceda; define errores previsibles y error arrastrado; fija reglas de unidades, signos, redondeo, cifras significativas y aproximaciones; máximo dos criterios por cuestión. Si faltan ponderaciones y no están autorizadas, usa max_points=null y scoring_status=blocked. Si están autorizadas, reparte razonadamente hasta %.4f puntos. Usa fmc_version=\"1\" y master_sha256=\"%s\".\n\n%s\n%s\n\nDEVUELVE EXCLUSIVAMENTE JSON VÁLIDO, sin markdown. Estructura mínima obligatoria: {\"exam_title\":string,\"fmc_version\":string,\"master_sha256\":string,\"scoring_status\":string,\"scientific_audit_summary\":string,\"blocking_issues\":[string],\"questions\":[{\"id\":string,\"question\":string,\"item_id\":string|null,\"max_points\":number|null,\"criteria\":[string],\"sabers\":[string],\"expected_answer\":string,\"evidence_matrix\":[{\"code\":string,\"description\":string,\"points\":number,\"essential\":boolean,\"partial_allowed\":boolean,\"partial_points\":number,\"cap_if_missing\":number|null}],\"audit_notes\":string}]}",
            title, unit, type, duration, total, level, presentation, sha, autoAllocate ? "AUTORIZADO reparto automático razonado" : "PROHIBIDO inventarlas", total, sha, CORE, CRITERIA);
    }

    public static String correction(String code, String level, String presentation, JSONObject fmc) {
        return "ACTÚA COMO CORRECTOR CRITERIAL DE QUÍMICA DE 2.º DE BACHILLERATO. Corrige las respuestas adjuntas usando EXCLUSIVAMENTE la FMC BLOQUEADA siguiente. No la modifiques.\n\nAlumno/pseudónimo: " + code + ". Exigencia: " + level + ". Presentación: " + presentation + ".\n\nREGLAS: corrige cada cuestión independientemente; para CADA evidencia de la FMC devuelve exactamente un estado entre ACREDITADA, PARCIALMENTE_ACREDITADA, NO_ACREDITADA, NO_EVALUABLE_ILEGIBILIDAD; PARCIALMENTE_ACREDITADA solo si la FMC la autorizó; no inventes ni omitas evidencias; resume evidencia observable y localízala; trata [ILEGIBLE], [DUDOSO], [AMBIGUO] y [ERROR ARRASTRADO] sin doble penalización; si una lectura dudosa puede cambiar más de 0,5 puntos, material_doubt=true y status=blocked; no otorgues puntos por conocimientos no expresados. La app recalculará localmente awarded_points.\n\n" + CORE + "\n\nFMC BLOQUEADA:\n" + fmc.toString() + "\n\nDEVUELVE EXCLUSIVAMENTE JSON VÁLIDO, sin markdown. Estructura mínima: {\"student_code\":string,\"fmc_version\":string,\"status\":string,\"question_results\":[{\"id\":string,\"question\":string,\"legibility\":string,\"student_response_summary\":string,\"evidence_vector\":[{\"code\":string,\"state\":string,\"evidence_location\":string}],\"errors\":[string],\"carried_error_treatment\":string,\"justification\":string,\"material_doubt\":boolean,\"comment\":string,\"confidence\":number}],\"presentation_penalty\":number,\"presentation_penalty_reason\":string,\"technical_report\":string,\"feedback\":[string],\"consistency_notes\":[string],\"blocking_issues\":[string]}";
    }
}
