plugins {
    id 'com.android.application'
}

android {
    namespace 'es.aulaevidencia.android'
    compileSdk 36

    defaultConfig {
        applicationId 'es.aulaevidencia.personal.stable'
        minSdk 26
        targetSdk 36
        versionCode 22
        versionName '1.2.19-docio'
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.biometric:biometric:1.1.0'
}
